# MultiChat - sistem format obrolan
general:
  # Bahasa pesan. Bahasa yang didukung:
  # eng - Inggris
  # idn - Indonesia
  language: idn
  # Simpan file terjemahan
  language-save: false
  # Mode debug. Biasanya Anda tidak perlu menyalakannya
  debug: false
chat:
  # Format obrolan standar
  format: '&f[&c%time%&f] &f[&a%prefix%&f] &f[%aMember&f] &f[&2%faction%&f] &f[&2%suffix%&f] &6%player%&f: &e%message%'
name-tag:
  # Format label nama standar
  enable: true
  format: '&f[&a%prefix%&f] &f[%aMember&f] &f[&2%faction%&f] &f[&2%suffix%&f] &6%player%'
  # Hapus kode warna dari label nama
  strip-colors: false
display-name:
  # Aktifkan tampilan nama (diperlihatkan oleh tombol TAB)
  enable: true
  format: '&f[&a%prefix%&f] &f[&2%suffix%&f] &6%player%'
  # Hapus kode warna dari tampilan nama
  strip-colors: false

# Konfigurasi format per pangkat
group:
  # Pindai sub pangkat (pangkat dalam pangkat)
  scan-subgroups: true
  # Format obrolan
  format:
    Owner: # Nama pangkat
      chat: '&f[&c%time%&f] &f[&4Owner&f] &f[&2%faction%&f] &6%player%&f: &a%message%' # Format obrolan
      name-tag: '&f[&c%time%&f] &f[&4Owner&f] &6%player%' # Format label nama