# ---------Konfigurasi Utama Robot Discord----------


# Versi Konfigurasi ini
configVersion: 2

# Masukan kode Robot Discord token yang dapat dibuat di https://discordapp.com/developers/applications/
botToken: "Masukan token Robot Discord"

# Masukan id saluran Robot Discord yang ingin kamu gunakan untuk Server
channelId: "Masukan id saluran"

# debug
debug: false

# -----------------Konfigurasi Dasar Robot Discord--------------------


# Mengaktifkan/Menonatifkan Robot Discord
enableBotStatus: true
# Nama Robot Discord
botStatus: ""

# Masukan topik saluran teks atau biarkan kosong agar menonaktifkan
channelTopic: ""

# Mengaktifkan/Menonatifkan perintah !playerlist
playerListCommand: true
# Mengaktifkan/Menonatifkan perintah !ip
ipCommand: true
# Masukan ip server
serverIp: "play.contoh.com"
# Masukan port server
serverPort: "19132"


# Mengaktifkan/Menonatifkan pesan masuk
joinMessages: true
# Mengaktifkan/Menonatifkan pesan keluar
quitMessages: true
# Mengaktifkan/Menonatifkan pesan kematian
deathMessages: true
# Mengaktifkan/Menonatifkan pesan jalankan server
startMessages: true
# Mengaktifkan/Menonatifkan pesan hentikan server
stopMessages: true


# Mengaktifkan/Menonatifkan pesan Robot Discord ke server
enableDiscordToMinecraft: true
# Mengaktifkan/Menonatifkan pesan server ke Robot Discord
enableMinecraftToDiscord: true
# Tampilkan pesan Robot Discord di konsol
enableMessagesToConsole: false


# Mengaktifkan/Menonatifkan Robot Discord konsol
discordConsole: false
# Id saluran konsol server Robot Discord
consoleChannelId: ""


# Format pesan Robot Discord yang ditampilkan dalam permainan
discordToMinecraftChatFormatting: ":star: %time% :envelope: %player_displayname% :star2:"
# Format pesan permainan ditampilkan di Robot Discord
minecraftToDiscordChatFormatting: ":star: %time% :envelope: %player_displayname% :star2:"


# Panjang pesan Robot Discord yang akan dipotong
maxMessageLength: 255
# Mengijinkan pesan yang dikirim oleh Robot ditampilkan di permainan
allowBotMessages: false
# Mengaktifkan/Menonatifkan filter spam
spamFilter: true


# terjemahan
discord_player_messages: ":star: [%time%] :star: [%world%] :star2: %player_displayname% :envelope: %player_message% :envelope:"
status_server_started: ":star: [%time%] :green_circle: Server Telah Aktif :green_circle:"
status_server_stopped: ":star: [%time%] :red_circle: Server Telah Mati :red_circle:"
info_player_joined: ":star: [%time%] :heavy_plus_sign: %player_displayname% Masuk Ke Server :heavy_plus_sign:"
info_player_left: ":star: [%time%] :heavy_minus_sign: %player_displayname% Keluar Ke Server :heavy_minus_sign:"
info_player_death: ":star: [%time%] :skull: %death_message% :skull:"
command_playerlist_empty: "Tidak Ada Pemain Online"
command_playerlist_players: "Pemain Online"
commands_ip_address: "IP:"
commands_ip_port: "Port:"
discord_prefix: "§f[§bDiscord%role%§f]"