name: NoteBlockMusic
main: Fahrul8676.noteblockmusic.NoteBlockMusicPlugin
description: "Plugin Lagu Blok Musik"
version: "1.14.0"
api: ["1.0.1"]
permissions:
  noteblockmusic.command.stopall:
    default: op