# tipe ada cencor, blocker, atau command
type: cencor

reply: "&bDilarang Bercakap &eKotor"

#cencorer
#blocker
words:
# Ucapan yang akan diganti dengan * dalam obrolan
# Ucapan yang akan diblokir dalam obrolan
 - Idiot
 - Tolol

message: "&bKamu Bicara Kotor Dan Terimalah &cHukuman&r"
broadcast: "&bPemain %p &bBicara Kotor Yaitu Perkataan &e%m&r"
#command
# Perintah untuk mengeksekusi;
command: kick @p §bKamu &bDikeluarkan Karena Bicara &eKotor&r